### Testaa käyttäjän kirjautuminen ja tallenna token
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "uusi",
  "password": "salakala"
}

### Lisää uusi harjoitus
POST http://localhost:3000/api/exercises
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6IlV1c2kiLCJwYXNzd29yZCI6IiQyYiQxMCROUlVLbUROdXRxRmMydmNVMjVuc1Z1MHZseEx2Q0xMOTllMklodjlDV1pNWGlLM1BMRGF0dSIsImVtYWlsIjoibmV3dXNlckBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTA5VDEzOjIyOjI1LjAwMFoiLCJ1c2VyX2xldmVsIjoxLCJpYXQiOjE3NDE1MjczNjQsImV4cCI6MTc0MTYxMzc2NH0.ASffDS7mDNYC1PqR0epQjF9EfB1ZujLU3gqwuJD9gTE

{
  "type": "Running",
  "duration": 30,
  "intensity": "Medium",
  "notes": "Felt great!"
}

### Hae kaikki harjoitukset
GET http://localhost:3000/api/exercises
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6IlV1c2kiLCJwYXNzd29yZCI6IiQyYiQxMCROUlVLbUROdXRxRmMydmNVMjVuc1Z1MHZseEx2Q0xMOTllMklodjlDV1pNWGlLM1BMRGF0dSIsImVtYWlsIjoibmV3dXNlckBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTA5VDEzOjIyOjI1LjAwMFoiLCJ1c2VyX2xldmVsIjoxLCJpYXQiOjE3NDE1MjczNjQsImV4cCI6MTc0MTYxMzc2NH0.ASffDS7mDNYC1PqR0epQjF9EfB1ZujLU3gqwuJD9gTE

### Lisää uusi mieliala
POST http://localhost:3000/api/moods
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6IlV1c2kiLCJwYXNzd29yZCI6IiQyYiQxMCROUlVLbUROdXRxRmMydmNVMjVuc1Z1MHZseEx2Q0xMOTllMklodjlDV1pNWGlLM1BMRGF0dSIsImVtYWlsIjoibmV3dXNlckBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTA5VDEzOjIyOjI1LjAwMFoiLCJ1c2VyX2xldmVsIjoxLCJpYXQiOjE3NDE1MjczNjQsImV4cCI6MTc0MTYxMzc2NH0.ASffDS7mDNYC1PqR0epQjF9EfB1ZujLU3gqwuJD9gTE

{
  "mood": "Happy",
  "notes": "Had a great day!"
}

### Hae kaikki mielialat
GET http://localhost:3000/api/moods
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6IlV1c2kiLCJwYXNzd29yZCI6IiQyYiQxMCROUlVLbUROdXRxRmMydmNVMjVuc1Z1MHZseEx2Q0xMOTllMklodjlDV1pNWGlLM1BMRGF0dSIsImVtYWlsIjoibmV3dXNlckBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTA5VDEzOjIyOjI1LjAwMFoiLCJ1c2VyX2xldmVsIjoxLCJpYXQiOjE3NDE1MjczNjQsImV4cCI6MTc0MTYxMzc2NH0.ASffDS7mDNYC1PqR0epQjF9EfB1ZujLU3gqwuJD9gTE

### Lisää uusi unipäiväkirjamerkintä
POST http://localhost:3000/api/entries
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6IlV1c2kiLCJwYXNzd29yZCI6IiQyYiQxMCROUlVLbUROdXRxRmMydmNVMjVuc1Z1MHZseEx2Q0xMOTllMklodjlDV1pNWGlLM1BMRGF0dSIsImVtYWlsIjoibmV3dXNlckBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTA5VDEzOjIyOjI1LjAwMFoiLCJ1c2VyX2xldmVsIjoxLCJpYXQiOjE3NDE1MjczNjQsImV4cCI6MTc0MTYxMzc2NH0.ASffDS7mDNYC1PqR0epQjF9EfB1ZujLU3gqwuJD9gTE

{
  "sleep_duration": 7.5,
  "sleep_quality": "Good",
  "dream_description": "Dreamt about flying",
  "ai_analysis": "Possible feeling of freedom and ambition"
}

### Hae kaikki unipäiväkirjamerkinnät
GET http://localhost:3000/api/entries
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6IlV1c2kiLCJwYXNzd29yZCI6IiQyYiQxMCROUlVLbUROdXRxRmMydmNVMjVuc1Z1MHZseEx2Q0xMOTllMklodjlDV1pNWGlLM1BMRGF0dSIsImVtYWlsIjoibmV3dXNlckBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTA5VDEzOjIyOjI1LjAwMFoiLCJ1c2VyX2xldmVsIjoxLCJpYXQiOjE3NDE1MjczNjQsImV4cCI6MTc0MTYxMzc2NH0.ASffDS7mDNYC1PqR0epQjF9EfB1ZujLU3gqwuJD9gTE
